#!/bin/bash

date
export PS4=' $SECONDS + '
set -xa

# PATH for working directory
export NET=${NET:-wave}
export RUN=${RUN:-gfs}
#export modID=${RUN}${NET}
export COMPONENTwave=${COMPONENTwave:-${RUN}${NET}}
export fstart=${fstart:-0}
export FHMAX_WAV=${FHMAX_WAV:-180}       #180 Total of hours to process
export FHMAX_HF_WAV=${FHMAX_HF_WAV:-72}  #from 00 to  72 inc=3
export FHOUT_WAV=${FHOUT_WAV:-6}         #from 72 to 180 inc=6
export FHOUT_HF_WAV=${FHOUT_HF_WAV:-3}
export maxtries=720


export HOMEwave=${HOMEwave:-$(dirname $(dirname $0))} # parent directory of current job card
export DATA=${DATA:-${DATAROOT:?}/${job}.$$}
mkdir -p $DATA
cd $DATA

cyc=${cyc:-00}
export cycle=${cycle:-t${cyc}z}
export pgmout=OUTPUT.$$
#export modID=${RUN}${NET}
export modID=${modID:-${RUN}${NET}}

####################################
# Path to HOME Directory
####################################

export CODEwave=${CODEwave:-${NWROOT}/${NET}_code.${wave_code_ver}/${code_pkg}}

export EXECwave=${EXECwave:-HOMEwave/exec}
export FIXwave=${FIXwave:-HOMEwave/fix}
export PARMwave=${PARMwave:-HOMEwave/parm}
export USHwave=${USHwave:-HOMEwave/ush}
export EXECcode=${EXECcode:-CODEwave/exec}

# Set PDY
setpdy.sh
. PDY
####################################
# load modules
####################################
module use ${HOMEwave}/modulefiles
module load modulefile_gfswave_prdgen.wcoss_dell_p3

###################################
# Set COM Paths and GETGES environment
###################################
export COMINwave=${COMINwave:-${COMROOT:?}/${NET}/${envir}}
export COMOUTwave=${COMOUTwave:-${COMROOT:?}/${NET}/${envir}}
export COMIN=${COMIN:-${COMINwave}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMOUTwave}/${RUN}.${PDY}}
export PCOM=${PCOM:-${COMOUT}/wmo}

if [ $SENDCOM = YES ]; then
  mkdir -p $COMOUT $PCOM
fi

export wavelog=${COMOUTwave}/wave.log

env

###################################
# Execute the Script  
###################################

$HOMEwave/scripts/exwave_prdgen_gridded.sh.ecf

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

